--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

CREATE OR REPLACE VIEW dv.product_subcategory_s
AS
SELECT
  product_subcategory_key
  ,max(load_dts) AS load_dts
  ,effective_ts
  ,name
  ,rec_src
FROM (
  
  SELECT
    src:ProductSubcategoryID::STRING AS product_subcategory_key
    ,CURRENT_TIMESTAMP AS load_dts
    ,src:ModifiedDate::TIMESTAMP AS effective_ts
    ,src:Name::STRING AS name
    ,'sales' AS rec_src
  FROM
    src_adventureworks.productsubcategory
)
GROUP BY
  product_subcategory_key
  ,effective_ts
  ,name
  ,rec_src
;