--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

CREATE OR REPLACE VIEW dv.product_main_s
AS
SELECT
  product_key
  ,max(load_dts) AS load_dts
  ,effective_ts
  ,name
  ,class
  ,color
  ,days_to_manufacture
  ,discontinued_date
  ,finished_goods_flag
  ,list_price
  ,make_flag
  ,product_line
  ,product_number
  ,reorder_point
  ,safety_stock_level
  ,sell_end_date
  ,sell_start_date
  ,size
  ,size_unit_measure_code
  ,standard_cost
  ,style
  ,weight
  ,weight_unit_measure_code
  ,rec_src
FROM (
  
  SELECT
    src:ProductID::STRING AS product_key
    ,CURRENT_TIMESTAMP AS load_dts
    ,src:ModifiedDate::TIMESTAMP AS effective_ts
    ,src:Name::STRING AS name
    ,src:Class::STRING AS class
    ,src:Color::STRING AS color
    ,src:DaysToManufacture::INT AS days_to_manufacture
    ,src:DiscontinuedDate::TIMESTAMP AS discontinued_date
    ,src:FinishedGoodsFlag::STRING AS finished_goods_flag
    ,src:ListPrice::NUMBER(18,4) AS list_price
    ,src:MakeFlag::STRING AS make_flag
    ,src:ProductLine::STRING AS product_line
    ,src:ProductNumber::STRING AS product_number
    ,src:ReorderPoint::INT AS reorder_point
    ,src:SafetyStockLevel::INT AS safety_stock_level
    ,src:SellEndDate::TIMESTAMP AS sell_end_date
    ,src:SellStartDate::TIMESTAMP AS sell_start_date
    ,src:Size::STRING AS size
    ,src:SizeUnitMeasureCode::STRING AS size_unit_measure_code
    ,src:StandardCost::NUMBER(18,4) AS standard_cost
    ,src:Style::STRING AS style
    ,src:Weight::NUMBER(18,4) AS weight
    ,src:WeightUnitMeasureCode::STRING AS weight_unit_measure_code
    ,'sales' AS rec_src
  FROM
    src_adventureworks.product
)
GROUP BY
  product_key
  ,effective_ts
  ,name
  ,class
  ,color
  ,days_to_manufacture
  ,discontinued_date
  ,finished_goods_flag
  ,list_price
  ,make_flag
  ,product_line
  ,product_number
  ,reorder_point
  ,safety_stock_level
  ,sell_end_date
  ,sell_start_date
  ,size
  ,size_unit_measure_code
  ,standard_cost
  ,style
  ,weight
  ,weight_unit_measure_code
  ,rec_src
;