--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

CREATE OR REPLACE VIEW dv.product_h
AS
SELECT
  product_key
  ,product_id
  ,load_dts
  ,rec_src
FROM (
  SELECT
    product_key
    ,product_id
    ,load_dts
    ,rec_src
    ,row_number() over(PARTITION BY product_key ORDER BY load_dts asc) rn
  FROM (
    
    SELECT
      src:ProductID::STRING AS product_key
      ,src:ProductID::STRING AS product_id
      ,CURRENT_TIMESTAMP AS load_dts
      ,'sales' AS rec_src
    FROM
      src_adventureworks.product
  )
)
WHERE rn = 1
;