--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

CREATE OR REPLACE VIEW dv.product_subcategory_h
AS
SELECT
  product_subcategory_key
  ,product_subcategory_id
  ,load_dts
  ,rec_src
FROM (
  SELECT
    product_subcategory_key
    ,product_subcategory_id
    ,load_dts
    ,rec_src
    ,row_number() over(PARTITION BY product_subcategory_key ORDER BY load_dts asc) rn
  FROM (
    
    SELECT
      src:ProductSubcategoryID::STRING AS product_subcategory_key
      ,src:ProductSubcategoryID::STRING AS product_subcategory_id
      ,CURRENT_TIMESTAMP AS load_dts
      ,'sales' AS rec_src
    FROM
      src_adventureworks.product
    UNION ALL
    SELECT
      src:ProductSubcategoryID::STRING AS product_subcategory_key
      ,src:ProductSubcategoryID::STRING AS product_subcategory_id
      ,CURRENT_TIMESTAMP AS load_dts
      ,'sales' AS rec_src
    FROM
      src_adventureworks.productsubcategory
  )
)
WHERE rn = 1
;