--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

CREATE OR REPLACE VIEW dv.product_product_subcategory_l
AS
SELECT
  product_product_subcategory_l_key
  ,product_key
  ,product_subcategory_key
  ,load_dts
  ,rec_src
FROM (
  SELECT
    product_product_subcategory_l_key
    ,product_key
    ,product_subcategory_key
    ,load_dts
    ,rec_src
    ,row_number() over(PARTITION BY product_product_subcategory_l_key ORDER BY load_dts asc) rn
  FROM (
    
    SELECT
      src:ProductID::STRING || '|' || src:ProductSubcategoryID::STRING AS product_product_subcategory_l_key
      ,src:ProductID::STRING AS product_key
      ,src:ProductSubcategoryID::STRING AS product_subcategory_key
      ,CURRENT_TIMESTAMP AS load_dts
      ,'sales' AS rec_src
    FROM src_adventureworks.product
  )
)
WHERE rn = 1
;