--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

CREATE OR REPLACE VIEW dv.sales_orderline_measures_s
AS
SELECT
  sales_orderline_key
  ,max(load_dts) AS load_dts
  ,effective_ts
  ,line_total
  ,order_qty
  ,unit_price
  ,unit_price_discount
  ,rec_src
FROM (
  
  SELECT
    src:SalesOrderDetailID::STRING AS sales_orderline_key
    ,CURRENT_TIMESTAMP AS load_dts
    ,src:ModifiedDate::TIMESTAMP AS effective_ts
    ,src:LineTotal::INT AS line_total
    ,src:OrderQty::NUMBER(18,4) AS order_qty
    ,src:UnitPrice::NUMBER(18,4) AS unit_price
    ,src:UnitPriceDiscount::NUMBER(18,4) AS unit_price_discount
    ,'sales' AS rec_src
  FROM
    src_adventureworks.salesorderdetail
)
GROUP BY
  sales_orderline_key
  ,effective_ts
  ,line_total
  ,order_qty
  ,unit_price
  ,unit_price_discount
  ,rec_src
;