--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

CREATE OR REPLACE VIEW dv.sales_sales_orderline_l
AS
SELECT
  sales_sales_orderline_l_key
  ,sales_key
  ,sales_orderline_key
  ,load_dts
  ,rec_src
FROM (
  SELECT
    sales_sales_orderline_l_key
    ,sales_key
    ,sales_orderline_key
    ,load_dts
    ,rec_src
    ,row_number() over(PARTITION BY sales_sales_orderline_l_key ORDER BY load_dts asc) rn
  FROM (
    
    SELECT
      src:SalesOrderID::STRING || '|' || src:SalesOrderDetailID::STRING AS sales_sales_orderline_l_key
      ,src:SalesOrderID::STRING AS sales_key
      ,src:SalesOrderDetailID::STRING AS sales_orderline_key
      ,CURRENT_TIMESTAMP AS load_dts
      ,'sales' AS rec_src
    FROM src_adventureworks.salesorderdetail
  )
)
WHERE rn = 1
;