--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

CREATE OR REPLACE VIEW dv.sales_context_s
AS
SELECT
  sales_key
  ,max(load_dts) AS load_dts
  ,effective_ts
  ,orderdate
  ,onlineorderflag
  ,status
  ,duedate
  ,rec_src
FROM (
  
  SELECT
    src:SalesOrderID::STRING AS sales_key
    ,CURRENT_TIMESTAMP AS load_dts
    ,src:ModifiedDate::TIMESTAMP AS effective_ts
    ,src:OrderDate::DATE AS orderdate
    ,src:OnlineOrderFlag::BOOLEAN AS onlineorderflag
    ,src:Status::STRING AS status
    ,src:DueDate::DATE AS duedate
    ,'sales' AS rec_src
  FROM
    src_adventureworks.salesorderheader
)
GROUP BY
  sales_key
  ,effective_ts
  ,orderdate
  ,onlineorderflag
  ,status
  ,duedate
  ,rec_src
;