--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

CREATE OR REPLACE VIEW dv.sales_orderline_product_l
AS
SELECT
  sales_orderline_product_l_key
  ,sales_orderline_key
  ,product_key
  ,load_dts
  ,rec_src
FROM (
  SELECT
    sales_orderline_product_l_key
    ,sales_orderline_key
    ,product_key
    ,load_dts
    ,rec_src
    ,row_number() over(PARTITION BY sales_orderline_product_l_key ORDER BY load_dts asc) rn
  FROM (
    
    SELECT
      src:SalesOrderDetailID::STRING || '|' || src:ProductID::STRING AS sales_orderline_product_l_key
      ,src:SalesOrderDetailID::STRING AS sales_orderline_key
      ,src:ProductID::STRING AS product_key
      ,CURRENT_TIMESTAMP AS load_dts
      ,'sales' AS rec_src
    FROM src_adventureworks.salesorderdetail
  )
)
WHERE rn = 1
;