--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

CREATE OR REPLACE VIEW dv.sales_h
AS
SELECT
  sales_key
  ,sales_id
  ,load_dts
  ,rec_src
FROM (
  SELECT
    sales_key
    ,sales_id
    ,load_dts
    ,rec_src
    ,row_number() over(PARTITION BY sales_key ORDER BY load_dts asc) rn
  FROM (
    
    SELECT
      src:SalesOrderID::STRING AS sales_key
      ,src:SalesOrderID::STRING AS sales_id
      ,CURRENT_TIMESTAMP AS load_dts
      ,'sales' AS rec_src
    FROM
      src_adventureworks.salesorderheader
  )
)
WHERE rn = 1
;